name: gobuild

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'collector/**'
jobs:
  gobuild_test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: run go build
        run: |
          cd collector/
          go build ./cmd/main.go
