name: gofmt

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'collector/**'
jobs:
  gofmt_test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: run gofmt test
        run: ./automation/gofmt.sh
